// flow-typed signature: db89ee8c2ff1fa78158e1efb9c48ceb7
// flow-typed version: <<STUB>>/apollo-engine_v^1.0.4/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-engine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-engine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-engine/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'apollo-engine/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'apollo-engine/lib/__tests__/engine-common' {
  declare module.exports: any;
}

declare module 'apollo-engine/lib/__tests__/engine-restify.test' {
  declare module.exports: any;
}

declare module 'apollo-engine/lib/__tests__/engine.test' {
  declare module.exports: any;
}

declare module 'apollo-engine/lib/__tests__/launcher.test' {
  declare module.exports: any;
}

declare module 'apollo-engine/lib/__tests__/schema' {
  declare module.exports: any;
}

declare module 'apollo-engine/lib/__tests__/util' {
  declare module.exports: any;
}

declare module 'apollo-engine/lib/engine' {
  declare module.exports: any;
}

declare module 'apollo-engine/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-engine/lib/launcher' {
  declare module.exports: any;
}

declare module 'apollo-engine/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-engine/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'apollo-engine/coverage/lcov-report/prettify'>;
}
declare module 'apollo-engine/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'apollo-engine/coverage/lcov-report/sorter'>;
}
declare module 'apollo-engine/lib/__tests__/engine-common.js' {
  declare module.exports: $Exports<'apollo-engine/lib/__tests__/engine-common'>;
}
declare module 'apollo-engine/lib/__tests__/engine-restify.test.js' {
  declare module.exports: $Exports<'apollo-engine/lib/__tests__/engine-restify.test'>;
}
declare module 'apollo-engine/lib/__tests__/engine.test.js' {
  declare module.exports: $Exports<'apollo-engine/lib/__tests__/engine.test'>;
}
declare module 'apollo-engine/lib/__tests__/launcher.test.js' {
  declare module.exports: $Exports<'apollo-engine/lib/__tests__/launcher.test'>;
}
declare module 'apollo-engine/lib/__tests__/schema.js' {
  declare module.exports: $Exports<'apollo-engine/lib/__tests__/schema'>;
}
declare module 'apollo-engine/lib/__tests__/util.js' {
  declare module.exports: $Exports<'apollo-engine/lib/__tests__/util'>;
}
declare module 'apollo-engine/lib/engine.js' {
  declare module.exports: $Exports<'apollo-engine/lib/engine'>;
}
declare module 'apollo-engine/lib/index.js' {
  declare module.exports: $Exports<'apollo-engine/lib/index'>;
}
declare module 'apollo-engine/lib/launcher.js' {
  declare module.exports: $Exports<'apollo-engine/lib/launcher'>;
}
declare module 'apollo-engine/lib/types.js' {
  declare module.exports: $Exports<'apollo-engine/lib/types'>;
}
