// flow-typed signature: 5c37092a2b8fdfc79491241fa735a3e9
// flow-typed version: <<STUB>>/apollo-link-batch-http_v^1.2.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-batch-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-batch-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-batch-http/dist/src/batchHttpLink' {
  declare module.exports: any;
}

declare module 'apollo-link-batch-http/dist/src/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link-batch-http/dist/tests/batchHttpLink' {
  declare module.exports: any;
}

declare module 'apollo-link-batch-http/dist/tests/tests' {
  declare module.exports: any;
}

declare module 'apollo-link-batch-http/lib/batchHttpLink' {
  declare module.exports: any;
}

declare module 'apollo-link-batch-http/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link-batch-http/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-link-batch-http/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-batch-http/dist/src/batchHttpLink.js' {
  declare module.exports: $Exports<'apollo-link-batch-http/dist/src/batchHttpLink'>;
}
declare module 'apollo-link-batch-http/dist/src/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link-batch-http/dist/src/bundle.umd'>;
}
declare module 'apollo-link-batch-http/dist/tests/batchHttpLink.js' {
  declare module.exports: $Exports<'apollo-link-batch-http/dist/tests/batchHttpLink'>;
}
declare module 'apollo-link-batch-http/dist/tests/tests.js' {
  declare module.exports: $Exports<'apollo-link-batch-http/dist/tests/tests'>;
}
declare module 'apollo-link-batch-http/lib/batchHttpLink.js' {
  declare module.exports: $Exports<'apollo-link-batch-http/lib/batchHttpLink'>;
}
declare module 'apollo-link-batch-http/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link-batch-http/lib/bundle.umd'>;
}
declare module 'apollo-link-batch-http/lib/index.js' {
  declare module.exports: $Exports<'apollo-link-batch-http/lib/index'>;
}
declare module 'apollo-link-batch-http/rollup.config.js' {
  declare module.exports: $Exports<'apollo-link-batch-http/rollup.config'>;
}
