// flow-typed signature: babc12d64b1b10ea3b1151db94172cbb
// flow-typed version: <<STUB>>/apollo-link-retry_v^2.2.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-retry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-retry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-retry/dist/src/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link-retry/dist/src/retryLink' {
  declare module.exports: any;
}

declare module 'apollo-link-retry/dist/tests/retryLink' {
  declare module.exports: any;
}

declare module 'apollo-link-retry/dist/tests/tests' {
  declare module.exports: any;
}

declare module 'apollo-link-retry/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link-retry/lib/delayFunction' {
  declare module.exports: any;
}

declare module 'apollo-link-retry/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-link-retry/lib/retryFunction' {
  declare module.exports: any;
}

declare module 'apollo-link-retry/lib/retryLink' {
  declare module.exports: any;
}

declare module 'apollo-link-retry/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-retry/dist/src/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link-retry/dist/src/bundle.umd'>;
}
declare module 'apollo-link-retry/dist/src/retryLink.js' {
  declare module.exports: $Exports<'apollo-link-retry/dist/src/retryLink'>;
}
declare module 'apollo-link-retry/dist/tests/retryLink.js' {
  declare module.exports: $Exports<'apollo-link-retry/dist/tests/retryLink'>;
}
declare module 'apollo-link-retry/dist/tests/tests.js' {
  declare module.exports: $Exports<'apollo-link-retry/dist/tests/tests'>;
}
declare module 'apollo-link-retry/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link-retry/lib/bundle.umd'>;
}
declare module 'apollo-link-retry/lib/delayFunction.js' {
  declare module.exports: $Exports<'apollo-link-retry/lib/delayFunction'>;
}
declare module 'apollo-link-retry/lib/index.js' {
  declare module.exports: $Exports<'apollo-link-retry/lib/index'>;
}
declare module 'apollo-link-retry/lib/retryFunction.js' {
  declare module.exports: $Exports<'apollo-link-retry/lib/retryFunction'>;
}
declare module 'apollo-link-retry/lib/retryLink.js' {
  declare module.exports: $Exports<'apollo-link-retry/lib/retryLink'>;
}
declare module 'apollo-link-retry/rollup.config.js' {
  declare module.exports: $Exports<'apollo-link-retry/rollup.config'>;
}
