// flow-typed signature: 20c3ecfb93b92bace90ca1a847919235
// flow-typed version: <<STUB>>/britecharts-react_v^0.2.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'britecharts-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'britecharts-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'britecharts-react/dist/britecharts-react.min' {
  declare module.exports: any;
}

declare module 'britecharts-react/Gruntfile' {
  declare module.exports: any;
}

declare module 'britecharts-react/lib/esm/Donut' {
  declare module.exports: any;
}

declare module 'britecharts-react/lib/esm/Legend' {
  declare module.exports: any;
}

declare module 'britecharts-react/lib/esm/StackedArea' {
  declare module.exports: any;
}

declare module 'britecharts-react/lib/esm/Tooltip' {
  declare module.exports: any;
}

declare module 'britecharts-react/lib/umd/Donut.min' {
  declare module.exports: any;
}

declare module 'britecharts-react/lib/umd/Legend.min' {
  declare module.exports: any;
}

declare module 'britecharts-react/lib/umd/StackedArea.min' {
  declare module.exports: any;
}

declare module 'britecharts-react/lib/umd/Tooltip.min' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/charts/constants' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/charts/donut/donutChart' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/charts/donut/DonutComponent' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/charts/helpers/configuration' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/charts/helpers/optimizedResize' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/charts/helpers/validation' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/charts/helpers/withResponsiveness' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/charts/index' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/charts/legend/LegendChart' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/charts/legend/LegendComponent' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/charts/stackedArea/stackedAreaChart' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/charts/stackedArea/StackedAreaComponent' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/charts/tooltip/tooltipChart' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/charts/tooltip/TooltipComponent' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/helpers/testData' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/tasks/release' {
  declare module.exports: any;
}

declare module 'britecharts-react/src/tasks/shell' {
  declare module.exports: any;
}

declare module 'britecharts-react/styleguide.config' {
  declare module.exports: any;
}

declare module 'britecharts-react/webpack.config' {
  declare module.exports: any;
}

declare module 'britecharts-react/webpack.parts' {
  declare module.exports: any;
}

// Filename aliases
declare module 'britecharts-react/dist/britecharts-react.min.js' {
  declare module.exports: $Exports<'britecharts-react/dist/britecharts-react.min'>;
}
declare module 'britecharts-react/Gruntfile.js' {
  declare module.exports: $Exports<'britecharts-react/Gruntfile'>;
}
declare module 'britecharts-react/lib/esm/Donut.js' {
  declare module.exports: $Exports<'britecharts-react/lib/esm/Donut'>;
}
declare module 'britecharts-react/lib/esm/Legend.js' {
  declare module.exports: $Exports<'britecharts-react/lib/esm/Legend'>;
}
declare module 'britecharts-react/lib/esm/StackedArea.js' {
  declare module.exports: $Exports<'britecharts-react/lib/esm/StackedArea'>;
}
declare module 'britecharts-react/lib/esm/Tooltip.js' {
  declare module.exports: $Exports<'britecharts-react/lib/esm/Tooltip'>;
}
declare module 'britecharts-react/lib/umd/Donut.min.js' {
  declare module.exports: $Exports<'britecharts-react/lib/umd/Donut.min'>;
}
declare module 'britecharts-react/lib/umd/Legend.min.js' {
  declare module.exports: $Exports<'britecharts-react/lib/umd/Legend.min'>;
}
declare module 'britecharts-react/lib/umd/StackedArea.min.js' {
  declare module.exports: $Exports<'britecharts-react/lib/umd/StackedArea.min'>;
}
declare module 'britecharts-react/lib/umd/Tooltip.min.js' {
  declare module.exports: $Exports<'britecharts-react/lib/umd/Tooltip.min'>;
}
declare module 'britecharts-react/src/charts/constants.js' {
  declare module.exports: $Exports<'britecharts-react/src/charts/constants'>;
}
declare module 'britecharts-react/src/charts/donut/donutChart.js' {
  declare module.exports: $Exports<'britecharts-react/src/charts/donut/donutChart'>;
}
declare module 'britecharts-react/src/charts/donut/DonutComponent.js' {
  declare module.exports: $Exports<'britecharts-react/src/charts/donut/DonutComponent'>;
}
declare module 'britecharts-react/src/charts/helpers/configuration.js' {
  declare module.exports: $Exports<'britecharts-react/src/charts/helpers/configuration'>;
}
declare module 'britecharts-react/src/charts/helpers/optimizedResize.js' {
  declare module.exports: $Exports<'britecharts-react/src/charts/helpers/optimizedResize'>;
}
declare module 'britecharts-react/src/charts/helpers/validation.js' {
  declare module.exports: $Exports<'britecharts-react/src/charts/helpers/validation'>;
}
declare module 'britecharts-react/src/charts/helpers/withResponsiveness.js' {
  declare module.exports: $Exports<'britecharts-react/src/charts/helpers/withResponsiveness'>;
}
declare module 'britecharts-react/src/charts/index.js' {
  declare module.exports: $Exports<'britecharts-react/src/charts/index'>;
}
declare module 'britecharts-react/src/charts/legend/LegendChart.js' {
  declare module.exports: $Exports<'britecharts-react/src/charts/legend/LegendChart'>;
}
declare module 'britecharts-react/src/charts/legend/LegendComponent.js' {
  declare module.exports: $Exports<'britecharts-react/src/charts/legend/LegendComponent'>;
}
declare module 'britecharts-react/src/charts/stackedArea/stackedAreaChart.js' {
  declare module.exports: $Exports<'britecharts-react/src/charts/stackedArea/stackedAreaChart'>;
}
declare module 'britecharts-react/src/charts/stackedArea/StackedAreaComponent.js' {
  declare module.exports: $Exports<'britecharts-react/src/charts/stackedArea/StackedAreaComponent'>;
}
declare module 'britecharts-react/src/charts/tooltip/tooltipChart.js' {
  declare module.exports: $Exports<'britecharts-react/src/charts/tooltip/tooltipChart'>;
}
declare module 'britecharts-react/src/charts/tooltip/TooltipComponent.js' {
  declare module.exports: $Exports<'britecharts-react/src/charts/tooltip/TooltipComponent'>;
}
declare module 'britecharts-react/src/helpers/testData.js' {
  declare module.exports: $Exports<'britecharts-react/src/helpers/testData'>;
}
declare module 'britecharts-react/src/tasks/release.js' {
  declare module.exports: $Exports<'britecharts-react/src/tasks/release'>;
}
declare module 'britecharts-react/src/tasks/shell.js' {
  declare module.exports: $Exports<'britecharts-react/src/tasks/shell'>;
}
declare module 'britecharts-react/styleguide.config.js' {
  declare module.exports: $Exports<'britecharts-react/styleguide.config'>;
}
declare module 'britecharts-react/webpack.config.js' {
  declare module.exports: $Exports<'britecharts-react/webpack.config'>;
}
declare module 'britecharts-react/webpack.parts.js' {
  declare module.exports: $Exports<'britecharts-react/webpack.parts'>;
}
