// flow-typed signature: c30250a8be0a6c9f564342d4b98aec6e
// flow-typed version: <<STUB>>/generator-ehi-compgen_v^1.4.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'generator-ehi-compgen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'generator-ehi-compgen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'generator-ehi-compgen/generators/app/index' {
  declare module.exports: any;
}

declare module 'generator-ehi-compgen/generators/app/templates/component' {
  declare module.exports: any;
}

declare module 'generator-ehi-compgen/generators/app/templates/index' {
  declare module.exports: any;
}

declare module 'generator-ehi-compgen/generators/class-all/index' {
  declare module.exports: any;
}

declare module 'generator-ehi-compgen/generators/class-all/templates/component' {
  declare module.exports: any;
}

declare module 'generator-ehi-compgen/generators/class-all/templates/index' {
  declare module.exports: any;
}

declare module 'generator-ehi-compgen/generators/class-apollo/index' {
  declare module.exports: any;
}

declare module 'generator-ehi-compgen/generators/class-apollo/templates/component' {
  declare module.exports: any;
}

declare module 'generator-ehi-compgen/generators/class-apollo/templates/index' {
  declare module.exports: any;
}

declare module 'generator-ehi-compgen/generators/class-redux/index' {
  declare module.exports: any;
}

declare module 'generator-ehi-compgen/generators/class-redux/templates/component' {
  declare module.exports: any;
}

declare module 'generator-ehi-compgen/generators/class-redux/templates/index' {
  declare module.exports: any;
}

declare module 'generator-ehi-compgen/generators/class/index' {
  declare module.exports: any;
}

declare module 'generator-ehi-compgen/generators/class/templates/component' {
  declare module.exports: any;
}

declare module 'generator-ehi-compgen/generators/class/templates/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'generator-ehi-compgen/generators/app/index.js' {
  declare module.exports: $Exports<'generator-ehi-compgen/generators/app/index'>;
}
declare module 'generator-ehi-compgen/generators/app/templates/component.jsx' {
  declare module.exports: $Exports<'generator-ehi-compgen/generators/app/templates/component'>;
}
declare module 'generator-ehi-compgen/generators/app/templates/index.js' {
  declare module.exports: $Exports<'generator-ehi-compgen/generators/app/templates/index'>;
}
declare module 'generator-ehi-compgen/generators/class-all/index.js' {
  declare module.exports: $Exports<'generator-ehi-compgen/generators/class-all/index'>;
}
declare module 'generator-ehi-compgen/generators/class-all/templates/component.jsx' {
  declare module.exports: $Exports<'generator-ehi-compgen/generators/class-all/templates/component'>;
}
declare module 'generator-ehi-compgen/generators/class-all/templates/index.js' {
  declare module.exports: $Exports<'generator-ehi-compgen/generators/class-all/templates/index'>;
}
declare module 'generator-ehi-compgen/generators/class-apollo/index.js' {
  declare module.exports: $Exports<'generator-ehi-compgen/generators/class-apollo/index'>;
}
declare module 'generator-ehi-compgen/generators/class-apollo/templates/component.jsx' {
  declare module.exports: $Exports<'generator-ehi-compgen/generators/class-apollo/templates/component'>;
}
declare module 'generator-ehi-compgen/generators/class-apollo/templates/index.js' {
  declare module.exports: $Exports<'generator-ehi-compgen/generators/class-apollo/templates/index'>;
}
declare module 'generator-ehi-compgen/generators/class-redux/index.js' {
  declare module.exports: $Exports<'generator-ehi-compgen/generators/class-redux/index'>;
}
declare module 'generator-ehi-compgen/generators/class-redux/templates/component.jsx' {
  declare module.exports: $Exports<'generator-ehi-compgen/generators/class-redux/templates/component'>;
}
declare module 'generator-ehi-compgen/generators/class-redux/templates/index.js' {
  declare module.exports: $Exports<'generator-ehi-compgen/generators/class-redux/templates/index'>;
}
declare module 'generator-ehi-compgen/generators/class/index.js' {
  declare module.exports: $Exports<'generator-ehi-compgen/generators/class/index'>;
}
declare module 'generator-ehi-compgen/generators/class/templates/component.jsx' {
  declare module.exports: $Exports<'generator-ehi-compgen/generators/class/templates/component'>;
}
declare module 'generator-ehi-compgen/generators/class/templates/index.js' {
  declare module.exports: $Exports<'generator-ehi-compgen/generators/class/templates/index'>;
}
