// flow-typed signature: a26dfdb92546dfe098eed27b9f9ee9e2
// flow-typed version: <<STUB>>/material-ui-credit-card-icons_v^3.2.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui-credit-card-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui-credit-card-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui-credit-card-icons/lib/Icon_AmericanExpress' {
  declare module.exports: any;
}

declare module 'material-ui-credit-card-icons/lib/Icon_CreditCardOutline' {
  declare module.exports: any;
}

declare module 'material-ui-credit-card-icons/lib/Icon_DinersClub' {
  declare module.exports: any;
}

declare module 'material-ui-credit-card-icons/lib/Icon_Discover' {
  declare module.exports: any;
}

declare module 'material-ui-credit-card-icons/lib/Icon_JCB' {
  declare module.exports: any;
}

declare module 'material-ui-credit-card-icons/lib/Icon_MasterCard' {
  declare module.exports: any;
}

declare module 'material-ui-credit-card-icons/lib/Icon_Visa' {
  declare module.exports: any;
}

declare module 'material-ui-credit-card-icons/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui-credit-card-icons/lib/Icon_AmericanExpress.js' {
  declare module.exports: $Exports<'material-ui-credit-card-icons/lib/Icon_AmericanExpress'>;
}
declare module 'material-ui-credit-card-icons/lib/Icon_CreditCardOutline.js' {
  declare module.exports: $Exports<'material-ui-credit-card-icons/lib/Icon_CreditCardOutline'>;
}
declare module 'material-ui-credit-card-icons/lib/Icon_DinersClub.js' {
  declare module.exports: $Exports<'material-ui-credit-card-icons/lib/Icon_DinersClub'>;
}
declare module 'material-ui-credit-card-icons/lib/Icon_Discover.js' {
  declare module.exports: $Exports<'material-ui-credit-card-icons/lib/Icon_Discover'>;
}
declare module 'material-ui-credit-card-icons/lib/Icon_JCB.js' {
  declare module.exports: $Exports<'material-ui-credit-card-icons/lib/Icon_JCB'>;
}
declare module 'material-ui-credit-card-icons/lib/Icon_MasterCard.js' {
  declare module.exports: $Exports<'material-ui-credit-card-icons/lib/Icon_MasterCard'>;
}
declare module 'material-ui-credit-card-icons/lib/Icon_Visa.js' {
  declare module.exports: $Exports<'material-ui-credit-card-icons/lib/Icon_Visa'>;
}
declare module 'material-ui-credit-card-icons/lib/index.js' {
  declare module.exports: $Exports<'material-ui-credit-card-icons/lib/index'>;
}
