// flow-typed signature: 030d75c00077fcb021af199492c4005e
// flow-typed version: <<STUB>>/open-graph_v^0.2.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'open-graph'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'open-graph' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'open-graph/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'open-graph/index' {
  declare module.exports: $Exports<'open-graph'>;
}
declare module 'open-graph/index.js' {
  declare module.exports: $Exports<'open-graph'>;
}
declare module 'open-graph/test.js' {
  declare module.exports: $Exports<'open-graph/test'>;
}
