// flow-typed signature: 174d31c192f1d5c7164531c0aa4b7c9d
// flow-typed version: <<STUB>>/react-microlink_v^2.0.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-microlink'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-microlink' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-microlink/lib/components/Card/CardAnimation' {
  declare module.exports: any;
}

declare module 'react-microlink/lib/components/Card/CardContent' {
  declare module.exports: any;
}

declare module 'react-microlink/lib/components/Card/CardEmptyState' {
  declare module.exports: any;
}

declare module 'react-microlink/lib/components/Card/CardMedia/Image' {
  declare module.exports: any;
}

declare module 'react-microlink/lib/components/Card/CardMedia/index' {
  declare module.exports: any;
}

declare module 'react-microlink/lib/components/Card/CardMedia/loader' {
  declare module.exports: any;
}

declare module 'react-microlink/lib/components/Card/CardMedia/Video/controls' {
  declare module.exports: any;
}

declare module 'react-microlink/lib/components/Card/CardMedia/Video/index' {
  declare module.exports: any;
}

declare module 'react-microlink/lib/components/Card/CardMedia/wrap' {
  declare module.exports: any;
}

declare module 'react-microlink/lib/components/Card/CardText' {
  declare module.exports: any;
}

declare module 'react-microlink/lib/components/Card/CardWrap' {
  declare module.exports: any;
}

declare module 'react-microlink/lib/components/Card/index' {
  declare module.exports: any;
}

declare module 'react-microlink/lib/index' {
  declare module.exports: any;
}

declare module 'react-microlink/lib/index.m' {
  declare module.exports: any;
}

declare module 'react-microlink/lib/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-microlink/lib/components/Card/CardAnimation.js' {
  declare module.exports: $Exports<'react-microlink/lib/components/Card/CardAnimation'>;
}
declare module 'react-microlink/lib/components/Card/CardContent.js' {
  declare module.exports: $Exports<'react-microlink/lib/components/Card/CardContent'>;
}
declare module 'react-microlink/lib/components/Card/CardEmptyState.js' {
  declare module.exports: $Exports<'react-microlink/lib/components/Card/CardEmptyState'>;
}
declare module 'react-microlink/lib/components/Card/CardMedia/Image.js' {
  declare module.exports: $Exports<'react-microlink/lib/components/Card/CardMedia/Image'>;
}
declare module 'react-microlink/lib/components/Card/CardMedia/index.js' {
  declare module.exports: $Exports<'react-microlink/lib/components/Card/CardMedia/index'>;
}
declare module 'react-microlink/lib/components/Card/CardMedia/loader.js' {
  declare module.exports: $Exports<'react-microlink/lib/components/Card/CardMedia/loader'>;
}
declare module 'react-microlink/lib/components/Card/CardMedia/Video/controls.js' {
  declare module.exports: $Exports<'react-microlink/lib/components/Card/CardMedia/Video/controls'>;
}
declare module 'react-microlink/lib/components/Card/CardMedia/Video/index.js' {
  declare module.exports: $Exports<'react-microlink/lib/components/Card/CardMedia/Video/index'>;
}
declare module 'react-microlink/lib/components/Card/CardMedia/wrap.js' {
  declare module.exports: $Exports<'react-microlink/lib/components/Card/CardMedia/wrap'>;
}
declare module 'react-microlink/lib/components/Card/CardText.js' {
  declare module.exports: $Exports<'react-microlink/lib/components/Card/CardText'>;
}
declare module 'react-microlink/lib/components/Card/CardWrap.js' {
  declare module.exports: $Exports<'react-microlink/lib/components/Card/CardWrap'>;
}
declare module 'react-microlink/lib/components/Card/index.js' {
  declare module.exports: $Exports<'react-microlink/lib/components/Card/index'>;
}
declare module 'react-microlink/lib/index.js' {
  declare module.exports: $Exports<'react-microlink/lib/index'>;
}
declare module 'react-microlink/lib/index.m.js' {
  declare module.exports: $Exports<'react-microlink/lib/index.m'>;
}
declare module 'react-microlink/lib/utils/index.js' {
  declare module.exports: $Exports<'react-microlink/lib/utils/index'>;
}
