// flow-typed signature: f44c9c7d1706b59b4b5d7719531356f8
// flow-typed version: <<STUB>>/react-async-script_v^0.9.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-async-script'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-async-script' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-async-script/lib/async-script-loader' {
  declare module.exports: any;
}

declare module 'react-async-script/src/async-script-loader' {
  declare module.exports: any;
}

declare module 'react-async-script/webpack.config.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-async-script/lib/async-script-loader.js' {
  declare module.exports: $Exports<'react-async-script/lib/async-script-loader'>;
}
declare module 'react-async-script/src/async-script-loader.js' {
  declare module.exports: $Exports<'react-async-script/src/async-script-loader'>;
}
declare module 'react-async-script/webpack.config.test.js' {
  declare module.exports: $Exports<'react-async-script/webpack.config.test'>;
}
