// flow-typed signature: b25aa25926e7bdbafac050386f510e53
// flow-typed version: <<STUB>>/react-image-crop_v^3.0.9/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-image-crop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-image-crop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-image-crop/demo/bundle' {
  declare module.exports: any;
}

declare module 'react-image-crop/demo/demo' {
  declare module.exports: any;
}

declare module 'react-image-crop/dist/ReactCrop' {
  declare module.exports: any;
}

declare module 'react-image-crop/dist/ReactCrop.min' {
  declare module.exports: any;
}

declare module 'react-image-crop/lib/ReactCrop' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-image-crop/demo/bundle.js' {
  declare module.exports: $Exports<'react-image-crop/demo/bundle'>;
}
declare module 'react-image-crop/demo/demo.js' {
  declare module.exports: $Exports<'react-image-crop/demo/demo'>;
}
declare module 'react-image-crop/dist/ReactCrop.js' {
  declare module.exports: $Exports<'react-image-crop/dist/ReactCrop'>;
}
declare module 'react-image-crop/dist/ReactCrop.min.js' {
  declare module.exports: $Exports<'react-image-crop/dist/ReactCrop.min'>;
}
declare module 'react-image-crop/index' {
  declare module.exports: $Exports<'react-image-crop'>;
}
declare module 'react-image-crop/index.js' {
  declare module.exports: $Exports<'react-image-crop'>;
}
declare module 'react-image-crop/lib/ReactCrop.js' {
  declare module.exports: $Exports<'react-image-crop/lib/ReactCrop'>;
}
