// flow-typed signature: 069003b69a20af0569e05121e3640229
// flow-typed version: <<STUB>>/searchkit_v^2.3.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'searchkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'searchkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'searchkit/lib/__test__/core/AccessorManagerSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/AccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/AnonymousAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/BaseQueryAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/CheckboxFilterAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/CustomHighlightAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/DynamicRangeAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/FacetAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/HierarchicalFacetAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/HighlightAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/HitsAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/NestedFacetAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/NoFiltersHitCountAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/NumericalOptionsAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/PageSizeAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/PaginationAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/QueryAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/RangeAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/ResetSearchAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/SortingAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/SourceFilterAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/StatefulAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/SuggestionsAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/accessors/ViewOptionsAccessorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/history/HistorySpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/field_context/ChildrenFieldContext.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/field_context/EmbeddedFieldContext.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/field_context/NestedFieldContext.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/ImmutableQuerySpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/aggregations/AggsContainerSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/aggregations/BucketAggregationsSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/aggregations/MetricAggregationsSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/aggregations/PipelineAggregationsSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/compound/BoolQueriesSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/compound/FilteredQuerySpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/full_text/MatchPhrasePrefixSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/full_text/MatchQuerySpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/full_text/MultiMatchQuerySpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/full_text/QueryStringSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/full_text/SimpleQueryStringSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/joining/HasChildQuerySpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/joining/HasParentQuerySpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/joining/NestedQuerySpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/term_level/ExistsQuerySpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/term_level/RangeQuerySpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/term_level/TermQuerySpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/query/query_dsl/term_level/TermsQuerySpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/react/blockSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/react/FastClickSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/react/LoadingComponentSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/react/RenderComponentSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/react/SearchkitComponentSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/react/SearchkitProviderSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/SearchkitManagerSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/SearchRequestSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/state/ArrayStateSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/state/LevelStateSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/state/ObjectStateSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/state/StateSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/state/ValueStateSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/support/EventEmitterSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/support/GuidGeneratorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/support/UtilsSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/transport/AxiosESTransportSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/__test__/core/transport/MockESTransportSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/__test__/TestHelpers' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/display/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/display/view-switcher/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/display/view-switcher/ViewSwitcherConfig' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/display/view-switcher/ViewSwitcherHits' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/display/view-switcher/ViewSwitcherHits.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/display/view-switcher/ViewSwitcherToggle' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/checkbox-filter/CheckboxFilter' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/checkbox-filter/CheckboxFilter.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/dynamic-range-filter/DynamicRangeFilter' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/dynamic-range-filter/DynamicRangeFilter.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/facet-filter/FacetFilter' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/facet-filter/FacetFilter.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/facet-filter/FacetFilterProps' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/facet-filter/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/facet-filter/MenuFilter' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/facet-filter/MenuFilter.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/facet-filter/RefinementListFilter' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/hierarchical-menu-filter/src/HierarchicalMenuFilter' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/hierarchical-menu-filter/test/HierarchicalMenuFilterSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/hierarchical-refinement-filter/src/HierarchicalRefinementFilter' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/hierarchical-refinement-filter/test/HierarchicalRefinementFilterSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/input-filter/InputFilter' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/input-filter/InputFilter.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/numeric-refinement-list-filter/src/NumericRefinementListFilter' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/numeric-refinement-list-filter/test/NumericRefinementListFilterSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/range-filter/src/RangeFilter' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/range-filter/test/RangeFilterSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/reset-filters/src/ResetFilters' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/reset-filters/test/ResetFiltersSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/selected-filters/GroupedSelectedFilters' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/selected-filters/GroupedSelectedFilters.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/selected-filters/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/selected-filters/SelectedFilters' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/selected-filters/SelectedFilters.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/tag-filter/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/tag-filter/TagFilter' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/tag-filter/TagFilter.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/tag-filter/TagFilterConfig' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/tag-filter/TagFilterList' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/filters/tag-filter/TagFilterList.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/hits-stats/src/HitsStats' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/hits-stats/test/HitsStatsSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/hits/src/Hits' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/hits/src/InitialLoader' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/hits/src/NoHits' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/hits/src/NoHitsDisplay' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/hits/src/NoHitsErrorDisplay' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/hits/test/HitsSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/hits/test/InitialLoaderSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/hits/test/NoHitsSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/page-size-selector/PageSizeSelector' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/page-size-selector/PageSizeSelector.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/pagination/src/Pagination' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/pagination/src/PaginationUtils' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/pagination/test/PaginationSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/search-box/SearchBox' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/search-box/Searchbox.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/sorting-selector/src/SortingSelector' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/search/sorting-selector/test/SortSelectorSpec' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/filter-group/FilterGroup' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/filter-group/FilterGroup.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/filter-group/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/layout/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/layout/Layout' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/layout/Layout.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/layout/Panel' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/layout/Panel.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/list/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/list/ItemComponents' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/list/ItemComponents.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/list/ItemHistogramList' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/list/ItemHistogramList.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/list/ItemListComponents' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/list/ItemListComponents.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/list/ListProps' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/list/MockList' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/list/Select' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/list/Select.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/list/TagCloud' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/list/TagCloud.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/range/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/range/MockRange' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/range/RangeComponents' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/range/RangeHistogram' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/range/RangeHistogram.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/range/RangeInput' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/range/RangeInput.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/range/RangeProps' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/range/RangeSlider' {
  declare module.exports: any;
}

declare module 'searchkit/lib/components/ui/range/RangeSlider.unit' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/AccessorManager' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/Accessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/AnonymousAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/BaseQueryAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/CheckboxFilterAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/CustomHighlightAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/DynamicRangeAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/FacetAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/FilterBasedAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/HierarchicalFacetAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/HighlightAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/HitsAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/NestedFacetAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/NoFiltersHitCountAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/NumericOptionsAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/PageSizeAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/PaginationAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/QueryAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/RangeAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/ResetSearchAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/SortingAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/SourceFilterAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/StatefulAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/SuggestionsAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/accessors/ViewOptionsAccessor' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/history' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/field_context/ChildrenFieldContext' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/field_context/EmbeddedFieldContext' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/field_context/FieldContext' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/field_context/FieldContextFactory' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/field_context/FieldOptions' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/field_context/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/field_context/NestedFieldContext' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/ImmutableQuery' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/aggregations/AggsContainer' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/aggregations/BucketAggregations' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/aggregations/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/aggregations/MetricAggregations' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/aggregations/PipelineAggregations' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/compound/BoolQueries' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/compound/FilteredQuery' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/compound/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/full_text/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/full_text/MatchPhrasePrefix' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/full_text/MatchQuery' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/full_text/MultiMatchQuery' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/full_text/QueryString' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/full_text/SimpleQueryString' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/joining/HasChildQuery' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/joining/HasParentQuery' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/joining/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/joining/NestedQuery' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/term_level/ExistsQuery' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/term_level/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/term_level/RangeQuery' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/term_level/TermQuery' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/query_dsl/term_level/TermsQuery' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/query/SelectedFilter' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/react/block' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/react/FastClick' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/react/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/react/LoadingComponent' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/react/RenderComponent' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/react/SearchkitComponent' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/react/SearchkitProvider' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/SearchkitManager' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/SearchkitVersion' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/SearchRequest' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/state/ArrayState' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/state/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/state/LevelState' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/state/ObjectState' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/state/State' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/state/ValueState' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/support/EventEmitter' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/support/GuidGenerator' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/support/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/support/Newable' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/support/Utils' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/transport/AxiosESTransport' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/transport/ESTransport' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/transport/index' {
  declare module.exports: any;
}

declare module 'searchkit/lib/core/transport/MockESTransport' {
  declare module.exports: any;
}

declare module 'searchkit/lib/index' {
  declare module.exports: any;
}

declare module 'searchkit/postcss.config' {
  declare module.exports: any;
}

declare module 'searchkit/release/bundle' {
  declare module.exports: any;
}

declare module 'searchkit/scripts/writeVersion' {
  declare module.exports: any;
}

declare module 'searchkit/src/components/__test__/JestEnzymeSerializer' {
  declare module.exports: any;
}

declare module 'searchkit/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'searchkit/lib/__test__/core/AccessorManagerSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/AccessorManagerSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/AccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/AccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/AnonymousAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/AnonymousAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/BaseQueryAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/BaseQueryAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/CheckboxFilterAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/CheckboxFilterAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/CustomHighlightAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/CustomHighlightAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/DynamicRangeAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/DynamicRangeAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/FacetAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/FacetAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/HierarchicalFacetAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/HierarchicalFacetAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/HighlightAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/HighlightAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/HitsAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/HitsAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/NestedFacetAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/NestedFacetAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/NoFiltersHitCountAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/NoFiltersHitCountAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/NumericalOptionsAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/NumericalOptionsAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/PageSizeAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/PageSizeAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/PaginationAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/PaginationAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/QueryAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/QueryAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/RangeAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/RangeAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/ResetSearchAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/ResetSearchAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/SortingAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/SortingAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/SourceFilterAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/SourceFilterAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/StatefulAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/StatefulAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/SuggestionsAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/SuggestionsAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/accessors/ViewOptionsAccessorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/accessors/ViewOptionsAccessorSpec'>;
}
declare module 'searchkit/lib/__test__/core/history/HistorySpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/history/HistorySpec'>;
}
declare module 'searchkit/lib/__test__/core/query/field_context/ChildrenFieldContext.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/field_context/ChildrenFieldContext.unit'>;
}
declare module 'searchkit/lib/__test__/core/query/field_context/EmbeddedFieldContext.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/field_context/EmbeddedFieldContext.unit'>;
}
declare module 'searchkit/lib/__test__/core/query/field_context/NestedFieldContext.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/field_context/NestedFieldContext.unit'>;
}
declare module 'searchkit/lib/__test__/core/query/ImmutableQuerySpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/ImmutableQuerySpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/aggregations/AggsContainerSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/aggregations/AggsContainerSpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/aggregations/BucketAggregationsSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/aggregations/BucketAggregationsSpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/aggregations/MetricAggregationsSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/aggregations/MetricAggregationsSpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/aggregations/PipelineAggregationsSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/aggregations/PipelineAggregationsSpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/compound/BoolQueriesSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/compound/BoolQueriesSpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/compound/FilteredQuerySpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/compound/FilteredQuerySpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/full_text/MatchPhrasePrefixSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/full_text/MatchPhrasePrefixSpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/full_text/MatchQuerySpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/full_text/MatchQuerySpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/full_text/MultiMatchQuerySpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/full_text/MultiMatchQuerySpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/full_text/QueryStringSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/full_text/QueryStringSpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/full_text/SimpleQueryStringSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/full_text/SimpleQueryStringSpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/joining/HasChildQuerySpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/joining/HasChildQuerySpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/joining/HasParentQuerySpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/joining/HasParentQuerySpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/joining/NestedQuerySpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/joining/NestedQuerySpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/term_level/ExistsQuerySpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/term_level/ExistsQuerySpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/term_level/RangeQuerySpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/term_level/RangeQuerySpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/term_level/TermQuerySpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/term_level/TermQuerySpec'>;
}
declare module 'searchkit/lib/__test__/core/query/query_dsl/term_level/TermsQuerySpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/query/query_dsl/term_level/TermsQuerySpec'>;
}
declare module 'searchkit/lib/__test__/core/react/blockSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/react/blockSpec'>;
}
declare module 'searchkit/lib/__test__/core/react/FastClickSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/react/FastClickSpec'>;
}
declare module 'searchkit/lib/__test__/core/react/LoadingComponentSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/react/LoadingComponentSpec'>;
}
declare module 'searchkit/lib/__test__/core/react/RenderComponentSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/react/RenderComponentSpec'>;
}
declare module 'searchkit/lib/__test__/core/react/SearchkitComponentSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/react/SearchkitComponentSpec'>;
}
declare module 'searchkit/lib/__test__/core/react/SearchkitProviderSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/react/SearchkitProviderSpec'>;
}
declare module 'searchkit/lib/__test__/core/SearchkitManagerSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/SearchkitManagerSpec'>;
}
declare module 'searchkit/lib/__test__/core/SearchRequestSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/SearchRequestSpec'>;
}
declare module 'searchkit/lib/__test__/core/state/ArrayStateSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/state/ArrayStateSpec'>;
}
declare module 'searchkit/lib/__test__/core/state/LevelStateSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/state/LevelStateSpec'>;
}
declare module 'searchkit/lib/__test__/core/state/ObjectStateSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/state/ObjectStateSpec'>;
}
declare module 'searchkit/lib/__test__/core/state/StateSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/state/StateSpec'>;
}
declare module 'searchkit/lib/__test__/core/state/ValueStateSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/state/ValueStateSpec'>;
}
declare module 'searchkit/lib/__test__/core/support/EventEmitterSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/support/EventEmitterSpec'>;
}
declare module 'searchkit/lib/__test__/core/support/GuidGeneratorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/support/GuidGeneratorSpec'>;
}
declare module 'searchkit/lib/__test__/core/support/UtilsSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/support/UtilsSpec'>;
}
declare module 'searchkit/lib/__test__/core/transport/AxiosESTransportSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/transport/AxiosESTransportSpec'>;
}
declare module 'searchkit/lib/__test__/core/transport/MockESTransportSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/__test__/core/transport/MockESTransportSpec'>;
}
declare module 'searchkit/lib/components/__test__/TestHelpers.js' {
  declare module.exports: $Exports<'searchkit/lib/components/__test__/TestHelpers'>;
}
declare module 'searchkit/lib/components/display/index.js' {
  declare module.exports: $Exports<'searchkit/lib/components/display/index'>;
}
declare module 'searchkit/lib/components/display/view-switcher/index.js' {
  declare module.exports: $Exports<'searchkit/lib/components/display/view-switcher/index'>;
}
declare module 'searchkit/lib/components/display/view-switcher/ViewSwitcherConfig.js' {
  declare module.exports: $Exports<'searchkit/lib/components/display/view-switcher/ViewSwitcherConfig'>;
}
declare module 'searchkit/lib/components/display/view-switcher/ViewSwitcherHits.js' {
  declare module.exports: $Exports<'searchkit/lib/components/display/view-switcher/ViewSwitcherHits'>;
}
declare module 'searchkit/lib/components/display/view-switcher/ViewSwitcherHits.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/display/view-switcher/ViewSwitcherHits.unit'>;
}
declare module 'searchkit/lib/components/display/view-switcher/ViewSwitcherToggle.js' {
  declare module.exports: $Exports<'searchkit/lib/components/display/view-switcher/ViewSwitcherToggle'>;
}
declare module 'searchkit/lib/components/index.js' {
  declare module.exports: $Exports<'searchkit/lib/components/index'>;
}
declare module 'searchkit/lib/components/search/filters/checkbox-filter/CheckboxFilter.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/checkbox-filter/CheckboxFilter'>;
}
declare module 'searchkit/lib/components/search/filters/checkbox-filter/CheckboxFilter.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/checkbox-filter/CheckboxFilter.unit'>;
}
declare module 'searchkit/lib/components/search/filters/dynamic-range-filter/DynamicRangeFilter.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/dynamic-range-filter/DynamicRangeFilter'>;
}
declare module 'searchkit/lib/components/search/filters/dynamic-range-filter/DynamicRangeFilter.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/dynamic-range-filter/DynamicRangeFilter.unit'>;
}
declare module 'searchkit/lib/components/search/filters/facet-filter/FacetFilter.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/facet-filter/FacetFilter'>;
}
declare module 'searchkit/lib/components/search/filters/facet-filter/FacetFilter.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/facet-filter/FacetFilter.unit'>;
}
declare module 'searchkit/lib/components/search/filters/facet-filter/FacetFilterProps.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/facet-filter/FacetFilterProps'>;
}
declare module 'searchkit/lib/components/search/filters/facet-filter/index.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/facet-filter/index'>;
}
declare module 'searchkit/lib/components/search/filters/facet-filter/MenuFilter.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/facet-filter/MenuFilter'>;
}
declare module 'searchkit/lib/components/search/filters/facet-filter/MenuFilter.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/facet-filter/MenuFilter.unit'>;
}
declare module 'searchkit/lib/components/search/filters/facet-filter/RefinementListFilter.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/facet-filter/RefinementListFilter'>;
}
declare module 'searchkit/lib/components/search/filters/hierarchical-menu-filter/src/HierarchicalMenuFilter.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/hierarchical-menu-filter/src/HierarchicalMenuFilter'>;
}
declare module 'searchkit/lib/components/search/filters/hierarchical-menu-filter/test/HierarchicalMenuFilterSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/hierarchical-menu-filter/test/HierarchicalMenuFilterSpec'>;
}
declare module 'searchkit/lib/components/search/filters/hierarchical-refinement-filter/src/HierarchicalRefinementFilter.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/hierarchical-refinement-filter/src/HierarchicalRefinementFilter'>;
}
declare module 'searchkit/lib/components/search/filters/hierarchical-refinement-filter/test/HierarchicalRefinementFilterSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/hierarchical-refinement-filter/test/HierarchicalRefinementFilterSpec'>;
}
declare module 'searchkit/lib/components/search/filters/input-filter/InputFilter.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/input-filter/InputFilter'>;
}
declare module 'searchkit/lib/components/search/filters/input-filter/InputFilter.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/input-filter/InputFilter.unit'>;
}
declare module 'searchkit/lib/components/search/filters/numeric-refinement-list-filter/src/NumericRefinementListFilter.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/numeric-refinement-list-filter/src/NumericRefinementListFilter'>;
}
declare module 'searchkit/lib/components/search/filters/numeric-refinement-list-filter/test/NumericRefinementListFilterSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/numeric-refinement-list-filter/test/NumericRefinementListFilterSpec'>;
}
declare module 'searchkit/lib/components/search/filters/range-filter/src/RangeFilter.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/range-filter/src/RangeFilter'>;
}
declare module 'searchkit/lib/components/search/filters/range-filter/test/RangeFilterSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/range-filter/test/RangeFilterSpec'>;
}
declare module 'searchkit/lib/components/search/filters/reset-filters/src/ResetFilters.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/reset-filters/src/ResetFilters'>;
}
declare module 'searchkit/lib/components/search/filters/reset-filters/test/ResetFiltersSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/reset-filters/test/ResetFiltersSpec'>;
}
declare module 'searchkit/lib/components/search/filters/selected-filters/GroupedSelectedFilters.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/selected-filters/GroupedSelectedFilters'>;
}
declare module 'searchkit/lib/components/search/filters/selected-filters/GroupedSelectedFilters.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/selected-filters/GroupedSelectedFilters.unit'>;
}
declare module 'searchkit/lib/components/search/filters/selected-filters/index.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/selected-filters/index'>;
}
declare module 'searchkit/lib/components/search/filters/selected-filters/SelectedFilters.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/selected-filters/SelectedFilters'>;
}
declare module 'searchkit/lib/components/search/filters/selected-filters/SelectedFilters.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/selected-filters/SelectedFilters.unit'>;
}
declare module 'searchkit/lib/components/search/filters/tag-filter/index.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/tag-filter/index'>;
}
declare module 'searchkit/lib/components/search/filters/tag-filter/TagFilter.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/tag-filter/TagFilter'>;
}
declare module 'searchkit/lib/components/search/filters/tag-filter/TagFilter.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/tag-filter/TagFilter.unit'>;
}
declare module 'searchkit/lib/components/search/filters/tag-filter/TagFilterConfig.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/tag-filter/TagFilterConfig'>;
}
declare module 'searchkit/lib/components/search/filters/tag-filter/TagFilterList.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/tag-filter/TagFilterList'>;
}
declare module 'searchkit/lib/components/search/filters/tag-filter/TagFilterList.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/filters/tag-filter/TagFilterList.unit'>;
}
declare module 'searchkit/lib/components/search/hits-stats/src/HitsStats.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/hits-stats/src/HitsStats'>;
}
declare module 'searchkit/lib/components/search/hits-stats/test/HitsStatsSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/hits-stats/test/HitsStatsSpec'>;
}
declare module 'searchkit/lib/components/search/hits/src/Hits.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/hits/src/Hits'>;
}
declare module 'searchkit/lib/components/search/hits/src/InitialLoader.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/hits/src/InitialLoader'>;
}
declare module 'searchkit/lib/components/search/hits/src/NoHits.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/hits/src/NoHits'>;
}
declare module 'searchkit/lib/components/search/hits/src/NoHitsDisplay.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/hits/src/NoHitsDisplay'>;
}
declare module 'searchkit/lib/components/search/hits/src/NoHitsErrorDisplay.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/hits/src/NoHitsErrorDisplay'>;
}
declare module 'searchkit/lib/components/search/hits/test/HitsSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/hits/test/HitsSpec'>;
}
declare module 'searchkit/lib/components/search/hits/test/InitialLoaderSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/hits/test/InitialLoaderSpec'>;
}
declare module 'searchkit/lib/components/search/hits/test/NoHitsSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/hits/test/NoHitsSpec'>;
}
declare module 'searchkit/lib/components/search/page-size-selector/PageSizeSelector.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/page-size-selector/PageSizeSelector'>;
}
declare module 'searchkit/lib/components/search/page-size-selector/PageSizeSelector.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/page-size-selector/PageSizeSelector.unit'>;
}
declare module 'searchkit/lib/components/search/pagination/src/Pagination.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/pagination/src/Pagination'>;
}
declare module 'searchkit/lib/components/search/pagination/src/PaginationUtils.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/pagination/src/PaginationUtils'>;
}
declare module 'searchkit/lib/components/search/pagination/test/PaginationSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/pagination/test/PaginationSpec'>;
}
declare module 'searchkit/lib/components/search/search-box/SearchBox.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/search-box/SearchBox'>;
}
declare module 'searchkit/lib/components/search/search-box/Searchbox.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/search-box/Searchbox.unit'>;
}
declare module 'searchkit/lib/components/search/sorting-selector/src/SortingSelector.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/sorting-selector/src/SortingSelector'>;
}
declare module 'searchkit/lib/components/search/sorting-selector/test/SortSelectorSpec.js' {
  declare module.exports: $Exports<'searchkit/lib/components/search/sorting-selector/test/SortSelectorSpec'>;
}
declare module 'searchkit/lib/components/ui/filter-group/FilterGroup.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/filter-group/FilterGroup'>;
}
declare module 'searchkit/lib/components/ui/filter-group/FilterGroup.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/filter-group/FilterGroup.unit'>;
}
declare module 'searchkit/lib/components/ui/filter-group/index.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/filter-group/index'>;
}
declare module 'searchkit/lib/components/ui/index.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/index'>;
}
declare module 'searchkit/lib/components/ui/layout/index.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/layout/index'>;
}
declare module 'searchkit/lib/components/ui/layout/Layout.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/layout/Layout'>;
}
declare module 'searchkit/lib/components/ui/layout/Layout.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/layout/Layout.unit'>;
}
declare module 'searchkit/lib/components/ui/layout/Panel.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/layout/Panel'>;
}
declare module 'searchkit/lib/components/ui/layout/Panel.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/layout/Panel.unit'>;
}
declare module 'searchkit/lib/components/ui/list/index.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/list/index'>;
}
declare module 'searchkit/lib/components/ui/list/ItemComponents.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/list/ItemComponents'>;
}
declare module 'searchkit/lib/components/ui/list/ItemComponents.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/list/ItemComponents.unit'>;
}
declare module 'searchkit/lib/components/ui/list/ItemHistogramList.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/list/ItemHistogramList'>;
}
declare module 'searchkit/lib/components/ui/list/ItemHistogramList.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/list/ItemHistogramList.unit'>;
}
declare module 'searchkit/lib/components/ui/list/ItemListComponents.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/list/ItemListComponents'>;
}
declare module 'searchkit/lib/components/ui/list/ItemListComponents.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/list/ItemListComponents.unit'>;
}
declare module 'searchkit/lib/components/ui/list/ListProps.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/list/ListProps'>;
}
declare module 'searchkit/lib/components/ui/list/MockList.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/list/MockList'>;
}
declare module 'searchkit/lib/components/ui/list/Select.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/list/Select'>;
}
declare module 'searchkit/lib/components/ui/list/Select.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/list/Select.unit'>;
}
declare module 'searchkit/lib/components/ui/list/TagCloud.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/list/TagCloud'>;
}
declare module 'searchkit/lib/components/ui/list/TagCloud.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/list/TagCloud.unit'>;
}
declare module 'searchkit/lib/components/ui/range/index.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/range/index'>;
}
declare module 'searchkit/lib/components/ui/range/MockRange.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/range/MockRange'>;
}
declare module 'searchkit/lib/components/ui/range/RangeComponents.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/range/RangeComponents'>;
}
declare module 'searchkit/lib/components/ui/range/RangeHistogram.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/range/RangeHistogram'>;
}
declare module 'searchkit/lib/components/ui/range/RangeHistogram.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/range/RangeHistogram.unit'>;
}
declare module 'searchkit/lib/components/ui/range/RangeInput.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/range/RangeInput'>;
}
declare module 'searchkit/lib/components/ui/range/RangeInput.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/range/RangeInput.unit'>;
}
declare module 'searchkit/lib/components/ui/range/RangeProps.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/range/RangeProps'>;
}
declare module 'searchkit/lib/components/ui/range/RangeSlider.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/range/RangeSlider'>;
}
declare module 'searchkit/lib/components/ui/range/RangeSlider.unit.js' {
  declare module.exports: $Exports<'searchkit/lib/components/ui/range/RangeSlider.unit'>;
}
declare module 'searchkit/lib/core/AccessorManager.js' {
  declare module.exports: $Exports<'searchkit/lib/core/AccessorManager'>;
}
declare module 'searchkit/lib/core/accessors/Accessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/Accessor'>;
}
declare module 'searchkit/lib/core/accessors/AnonymousAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/AnonymousAccessor'>;
}
declare module 'searchkit/lib/core/accessors/BaseQueryAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/BaseQueryAccessor'>;
}
declare module 'searchkit/lib/core/accessors/CheckboxFilterAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/CheckboxFilterAccessor'>;
}
declare module 'searchkit/lib/core/accessors/CustomHighlightAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/CustomHighlightAccessor'>;
}
declare module 'searchkit/lib/core/accessors/DynamicRangeAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/DynamicRangeAccessor'>;
}
declare module 'searchkit/lib/core/accessors/FacetAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/FacetAccessor'>;
}
declare module 'searchkit/lib/core/accessors/FilterBasedAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/FilterBasedAccessor'>;
}
declare module 'searchkit/lib/core/accessors/HierarchicalFacetAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/HierarchicalFacetAccessor'>;
}
declare module 'searchkit/lib/core/accessors/HighlightAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/HighlightAccessor'>;
}
declare module 'searchkit/lib/core/accessors/HitsAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/HitsAccessor'>;
}
declare module 'searchkit/lib/core/accessors/index.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/index'>;
}
declare module 'searchkit/lib/core/accessors/NestedFacetAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/NestedFacetAccessor'>;
}
declare module 'searchkit/lib/core/accessors/NoFiltersHitCountAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/NoFiltersHitCountAccessor'>;
}
declare module 'searchkit/lib/core/accessors/NumericOptionsAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/NumericOptionsAccessor'>;
}
declare module 'searchkit/lib/core/accessors/PageSizeAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/PageSizeAccessor'>;
}
declare module 'searchkit/lib/core/accessors/PaginationAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/PaginationAccessor'>;
}
declare module 'searchkit/lib/core/accessors/QueryAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/QueryAccessor'>;
}
declare module 'searchkit/lib/core/accessors/RangeAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/RangeAccessor'>;
}
declare module 'searchkit/lib/core/accessors/ResetSearchAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/ResetSearchAccessor'>;
}
declare module 'searchkit/lib/core/accessors/SortingAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/SortingAccessor'>;
}
declare module 'searchkit/lib/core/accessors/SourceFilterAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/SourceFilterAccessor'>;
}
declare module 'searchkit/lib/core/accessors/StatefulAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/StatefulAccessor'>;
}
declare module 'searchkit/lib/core/accessors/SuggestionsAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/SuggestionsAccessor'>;
}
declare module 'searchkit/lib/core/accessors/ViewOptionsAccessor.js' {
  declare module.exports: $Exports<'searchkit/lib/core/accessors/ViewOptionsAccessor'>;
}
declare module 'searchkit/lib/core/history.js' {
  declare module.exports: $Exports<'searchkit/lib/core/history'>;
}
declare module 'searchkit/lib/core/index.js' {
  declare module.exports: $Exports<'searchkit/lib/core/index'>;
}
declare module 'searchkit/lib/core/query/field_context/ChildrenFieldContext.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/field_context/ChildrenFieldContext'>;
}
declare module 'searchkit/lib/core/query/field_context/EmbeddedFieldContext.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/field_context/EmbeddedFieldContext'>;
}
declare module 'searchkit/lib/core/query/field_context/FieldContext.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/field_context/FieldContext'>;
}
declare module 'searchkit/lib/core/query/field_context/FieldContextFactory.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/field_context/FieldContextFactory'>;
}
declare module 'searchkit/lib/core/query/field_context/FieldOptions.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/field_context/FieldOptions'>;
}
declare module 'searchkit/lib/core/query/field_context/index.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/field_context/index'>;
}
declare module 'searchkit/lib/core/query/field_context/NestedFieldContext.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/field_context/NestedFieldContext'>;
}
declare module 'searchkit/lib/core/query/ImmutableQuery.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/ImmutableQuery'>;
}
declare module 'searchkit/lib/core/query/index.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/index'>;
}
declare module 'searchkit/lib/core/query/query_dsl/aggregations/AggsContainer.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/aggregations/AggsContainer'>;
}
declare module 'searchkit/lib/core/query/query_dsl/aggregations/BucketAggregations.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/aggregations/BucketAggregations'>;
}
declare module 'searchkit/lib/core/query/query_dsl/aggregations/index.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/aggregations/index'>;
}
declare module 'searchkit/lib/core/query/query_dsl/aggregations/MetricAggregations.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/aggregations/MetricAggregations'>;
}
declare module 'searchkit/lib/core/query/query_dsl/aggregations/PipelineAggregations.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/aggregations/PipelineAggregations'>;
}
declare module 'searchkit/lib/core/query/query_dsl/compound/BoolQueries.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/compound/BoolQueries'>;
}
declare module 'searchkit/lib/core/query/query_dsl/compound/FilteredQuery.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/compound/FilteredQuery'>;
}
declare module 'searchkit/lib/core/query/query_dsl/compound/index.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/compound/index'>;
}
declare module 'searchkit/lib/core/query/query_dsl/full_text/index.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/full_text/index'>;
}
declare module 'searchkit/lib/core/query/query_dsl/full_text/MatchPhrasePrefix.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/full_text/MatchPhrasePrefix'>;
}
declare module 'searchkit/lib/core/query/query_dsl/full_text/MatchQuery.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/full_text/MatchQuery'>;
}
declare module 'searchkit/lib/core/query/query_dsl/full_text/MultiMatchQuery.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/full_text/MultiMatchQuery'>;
}
declare module 'searchkit/lib/core/query/query_dsl/full_text/QueryString.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/full_text/QueryString'>;
}
declare module 'searchkit/lib/core/query/query_dsl/full_text/SimpleQueryString.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/full_text/SimpleQueryString'>;
}
declare module 'searchkit/lib/core/query/query_dsl/index.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/index'>;
}
declare module 'searchkit/lib/core/query/query_dsl/joining/HasChildQuery.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/joining/HasChildQuery'>;
}
declare module 'searchkit/lib/core/query/query_dsl/joining/HasParentQuery.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/joining/HasParentQuery'>;
}
declare module 'searchkit/lib/core/query/query_dsl/joining/index.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/joining/index'>;
}
declare module 'searchkit/lib/core/query/query_dsl/joining/NestedQuery.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/joining/NestedQuery'>;
}
declare module 'searchkit/lib/core/query/query_dsl/term_level/ExistsQuery.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/term_level/ExistsQuery'>;
}
declare module 'searchkit/lib/core/query/query_dsl/term_level/index.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/term_level/index'>;
}
declare module 'searchkit/lib/core/query/query_dsl/term_level/RangeQuery.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/term_level/RangeQuery'>;
}
declare module 'searchkit/lib/core/query/query_dsl/term_level/TermQuery.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/term_level/TermQuery'>;
}
declare module 'searchkit/lib/core/query/query_dsl/term_level/TermsQuery.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/query_dsl/term_level/TermsQuery'>;
}
declare module 'searchkit/lib/core/query/SelectedFilter.js' {
  declare module.exports: $Exports<'searchkit/lib/core/query/SelectedFilter'>;
}
declare module 'searchkit/lib/core/react/block.js' {
  declare module.exports: $Exports<'searchkit/lib/core/react/block'>;
}
declare module 'searchkit/lib/core/react/FastClick.js' {
  declare module.exports: $Exports<'searchkit/lib/core/react/FastClick'>;
}
declare module 'searchkit/lib/core/react/index.js' {
  declare module.exports: $Exports<'searchkit/lib/core/react/index'>;
}
declare module 'searchkit/lib/core/react/LoadingComponent.js' {
  declare module.exports: $Exports<'searchkit/lib/core/react/LoadingComponent'>;
}
declare module 'searchkit/lib/core/react/RenderComponent.js' {
  declare module.exports: $Exports<'searchkit/lib/core/react/RenderComponent'>;
}
declare module 'searchkit/lib/core/react/SearchkitComponent.js' {
  declare module.exports: $Exports<'searchkit/lib/core/react/SearchkitComponent'>;
}
declare module 'searchkit/lib/core/react/SearchkitProvider.js' {
  declare module.exports: $Exports<'searchkit/lib/core/react/SearchkitProvider'>;
}
declare module 'searchkit/lib/core/SearchkitManager.js' {
  declare module.exports: $Exports<'searchkit/lib/core/SearchkitManager'>;
}
declare module 'searchkit/lib/core/SearchkitVersion.js' {
  declare module.exports: $Exports<'searchkit/lib/core/SearchkitVersion'>;
}
declare module 'searchkit/lib/core/SearchRequest.js' {
  declare module.exports: $Exports<'searchkit/lib/core/SearchRequest'>;
}
declare module 'searchkit/lib/core/state/ArrayState.js' {
  declare module.exports: $Exports<'searchkit/lib/core/state/ArrayState'>;
}
declare module 'searchkit/lib/core/state/index.js' {
  declare module.exports: $Exports<'searchkit/lib/core/state/index'>;
}
declare module 'searchkit/lib/core/state/LevelState.js' {
  declare module.exports: $Exports<'searchkit/lib/core/state/LevelState'>;
}
declare module 'searchkit/lib/core/state/ObjectState.js' {
  declare module.exports: $Exports<'searchkit/lib/core/state/ObjectState'>;
}
declare module 'searchkit/lib/core/state/State.js' {
  declare module.exports: $Exports<'searchkit/lib/core/state/State'>;
}
declare module 'searchkit/lib/core/state/ValueState.js' {
  declare module.exports: $Exports<'searchkit/lib/core/state/ValueState'>;
}
declare module 'searchkit/lib/core/support/EventEmitter.js' {
  declare module.exports: $Exports<'searchkit/lib/core/support/EventEmitter'>;
}
declare module 'searchkit/lib/core/support/GuidGenerator.js' {
  declare module.exports: $Exports<'searchkit/lib/core/support/GuidGenerator'>;
}
declare module 'searchkit/lib/core/support/index.js' {
  declare module.exports: $Exports<'searchkit/lib/core/support/index'>;
}
declare module 'searchkit/lib/core/support/Newable.js' {
  declare module.exports: $Exports<'searchkit/lib/core/support/Newable'>;
}
declare module 'searchkit/lib/core/support/Utils.js' {
  declare module.exports: $Exports<'searchkit/lib/core/support/Utils'>;
}
declare module 'searchkit/lib/core/transport/AxiosESTransport.js' {
  declare module.exports: $Exports<'searchkit/lib/core/transport/AxiosESTransport'>;
}
declare module 'searchkit/lib/core/transport/ESTransport.js' {
  declare module.exports: $Exports<'searchkit/lib/core/transport/ESTransport'>;
}
declare module 'searchkit/lib/core/transport/index.js' {
  declare module.exports: $Exports<'searchkit/lib/core/transport/index'>;
}
declare module 'searchkit/lib/core/transport/MockESTransport.js' {
  declare module.exports: $Exports<'searchkit/lib/core/transport/MockESTransport'>;
}
declare module 'searchkit/lib/index.js' {
  declare module.exports: $Exports<'searchkit/lib/index'>;
}
declare module 'searchkit/postcss.config.js' {
  declare module.exports: $Exports<'searchkit/postcss.config'>;
}
declare module 'searchkit/release/bundle.js' {
  declare module.exports: $Exports<'searchkit/release/bundle'>;
}
declare module 'searchkit/scripts/writeVersion.js' {
  declare module.exports: $Exports<'searchkit/scripts/writeVersion'>;
}
declare module 'searchkit/src/components/__test__/JestEnzymeSerializer.js' {
  declare module.exports: $Exports<'searchkit/src/components/__test__/JestEnzymeSerializer'>;
}
declare module 'searchkit/webpack.config.js' {
  declare module.exports: $Exports<'searchkit/webpack.config'>;
}
