export const states = [
  '',
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'District of Columbia (DC)',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
];
export const recreational = [
  'Califorina',
  'Washington',
  'District of Columbia (DC)',
  'Oregon',
  'Nevada',
  'Colorado',
  'Alaska',
  'Maine',
  'Massachusetts',
];
export const medical = [
  'Montana',
  'North Dakota',
  'Minnesota',
  'Ohio',
  'Pennsylvania',
  'New York',
  'Vermont',
  'New Hampshire',
  'Connecticut',
  'Rhode Island',
  'New Jersey',
  'Delaware',
  'Maryland',
  'Illinois',
  'Arizona',
  'New Mexico',
  'Arkansas',
  'Louisiana',
  'Florida',
  'Hawaii',
];
export const illegal = [
  'Idaho',
  'Utah',
  'Wyoming',
  'South Dakota',
  'Nebraska',
  'Kansas',
  'Oklahoma',
  'Texas',
  'Missouri',
  'Iowa',
  'Wisconsin',
  'Indiana',
  'Kentucky',
  'Tennessee',
  'Missisippi',
  'Alabama',
  'Georgia',
  'South Coroling',
  'North Coroling',
  'Virginia',
  'West Virginia',
];
